
import React from "react";
import { Card, CardContent } from "@/components/ui/card";

const TermsPage = () => {
  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
      
      <Card className="mb-6">
        <CardContent className="pt-6">
          <h2 className="text-xl font-semibold mb-4">1. Agreement to Terms</h2>
          <p>
            By accessing and using TrendScribe ("the Service"), you agree to be bound by these Terms and Conditions, 
            our Privacy Policy, and any other terms referenced herein. If you do not agree with any of these terms, 
            you are prohibited from using the Service.
          </p>
        </CardContent>
      </Card>
      
      <Card className="mb-6">
        <CardContent className="pt-6">
          <h2 className="text-xl font-semibold mb-4">2. Use License</h2>
          <p className="mb-4">
            Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, 
            non-sublicensable license to access and use the Service for your personal or business purposes.
          </p>
          <p>
            You may not:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Modify or copy the materials except as necessary for your authorized use of the Service</li>
            <li>Use the materials for any commercial purpose other than as expressly permitted</li>
            <li>Attempt to decompile or reverse engineer any software contained on TrendScribe</li>
            <li>Remove any copyright or other proprietary notations from the materials</li>
            <li>Transfer the materials to another person or "mirror" the materials on any other server</li>
          </ul>
        </CardContent>
      </Card>
      
      <Card className="mb-6">
        <CardContent className="pt-6">
          <h2 className="text-xl font-semibold mb-4">3. Account Responsibilities</h2>
          <p className="mb-4">
            When you create an account with us, you must provide information that is accurate, complete, and current at all times. 
            Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.
          </p>
          <p className="mb-4">
            You are responsible for safeguarding the password that you use to access the Service and for any activities or actions 
            under your password. You agree not to disclose your password to any third party.
          </p>
          <p>
            You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
          </p>
        </CardContent>
      </Card>
      
      <Card className="mb-6">
        <CardContent className="pt-6">
          <h2 className="text-xl font-semibold mb-4">4. Content Generated by the Service</h2>
          <p className="mb-4">
            You acknowledge that content generated through TrendScribe is created using artificial intelligence and may require 
            review and editing before publication.
          </p>
          <p className="mb-4">
            You retain all rights to content generated for you through the Service, subject to your payment of any applicable fees.
            However, we are not responsible for any consequences that may arise from your use of the generated content, including
            but not limited to copyright claims, accuracy issues, or suitability for specific purposes.
          </p>
          <p>
            You are solely responsible for ensuring that any content published complies with applicable laws and regulations, 
            including copyright laws, defamation laws, and industry-specific regulations.
          </p>
        </CardContent>
      </Card>
      
      <Card className="mb-6">
        <CardContent className="pt-6">
          <h2 className="text-xl font-semibold mb-4">5. Service Modifications</h2>
          <p>
            TrendScribe reserves the right to modify or discontinue, temporarily or permanently, the Service with or without notice. 
            We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.
          </p>
        </CardContent>
      </Card>
      
      <Card className="mb-6">
        <CardContent className="pt-6">
          <h2 className="text-xl font-semibold mb-4">6. Limitation of Liability</h2>
          <p>
            In no event shall TrendScribe, its officers, directors, employees, or agents be liable for any indirect, incidental, 
            special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or 
            other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>
        </CardContent>
      </Card>
      
      <Card>
        <CardContent className="pt-6">
          <h2 className="text-xl font-semibold mb-4">7. Governing Law</h2>
          <p>
            These Terms shall be governed by and defined following the laws of [Your Country/State]. TrendScribe and yourself 
            irrevocably consent to the exclusive jurisdiction of the courts in [Your City/State] for any action arising out of or 
            relating to these Terms.
          </p>
        </CardContent>
      </Card>
    </div>
  );
};

export default TermsPage;
