
import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FaqSection = () => {
  return (
    <section className="py-20 px-6 md:px-10 bg-muted/30">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Frequently Asked Questions</h2>
          <p className="text-xl text-muted-foreground">
            Everything you need to know about TrendScribe
          </p>
        </div>

        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="item-1">
            <AccordionTrigger>Is the content unique and SEO-friendly?</AccordionTrigger>
            <AccordionContent>
              Yes! All content generated by TrendScribe is completely unique and optimized for search engines. 
              Our AI models are trained to create original content while maintaining readability and SEO best practices.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger>How does the WordPress integration work?</AccordionTrigger>
            <AccordionContent>
              TrendScribe connects directly to your WordPress site using your credentials. You can publish 
              posts as drafts or schedule them automatically. The integration supports featured images, 
              categories, tags, and custom post types.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger>Which AI models are available?</AccordionTrigger>
            <AccordionContent>
              TrendScribe supports multiple AI models through OpenRouter, including Claude, GPT models, 
              and others. You can select the model that best fits your needs based on quality, speed, and cost.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger>How many RSS feeds can I add?</AccordionTrigger>
            <AccordionContent>
              You can add unlimited RSS feeds to your TrendScribe account. This allows you to monitor 
              multiple sources for content ideas across different niches and industries.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger>Can I customize the tone and style of generated content?</AccordionTrigger>
            <AccordionContent>
              Absolutely! TrendScribe offers extensive customization options including tone (professional, 
              conversational, enthusiastic, etc.), content length, output format, and more.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-6">
            <AccordionTrigger>Is there a limit to how many articles I can generate?</AccordionTrigger>
            <AccordionContent>
              TrendScribe offers different pricing plans with varying content generation limits. Our premium 
              plans provide higher limits and additional features for power users and agencies.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </section>
  );
};

export default FaqSection;
