// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovxccwhzghdkhqzvdbbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92eGNjd2h6Z2hka2hxenZkYmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTQ4NjgsImV4cCI6MjA1OTkzMDg2OH0.qaSM1hqU5B_XldpUzkA5JKIdvPEXRY890ecFdbG17xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);