// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylbwhbsqsbvjlqnsgemq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsYndoYnNxc2J2amxxbnNnZW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTA4NDksImV4cCI6MjA1OTc2Njg0OX0.5N9P6NmJSwIUHIE0WuBNxV-YjkI5ENwQwJgT_XOz4Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);